// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class Approval
{
    public long ApprovalId { get; set; }

    public string ReferenceType { get; set; }

    public long? ReferenceId { get; set; }

    public int? ApproverId { get; set; }

    public string ApprovalStatus { get; set; }

    public string Remarks { get; set; }

    public DateTime? ApprovedAt { get; set; }
}