// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class Bpjsconfiguration
{
    public int BpjsconfigId { get; set; }

    public string ConfigName { get; set; }

    public decimal? EmployeePercentage { get; set; }

    public decimal? CompanyPercentage { get; set; }

    public DateOnly? EffectiveDate { get; set; }
}