// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string EmployeeCode { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Gender { get; set; }

    public DateOnly? BirthDate { get; set; }

    public DateOnly HireDate { get; set; }

    public DateOnly? ResignDate { get; set; }

    public int? DepartmentId { get; set; }

    public int? PositionId { get; set; }

    public string BankName { get; set; }

    public string BankAccountNumber { get; set; }

    public string Npwp { get; set; }

    public decimal BasicSalary { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; } = new List<EmployeeLeaf>();

    public virtual ICollection<EmployeeThr> EmployeeThrs { get; set; } = new List<EmployeeThr>();

    public virtual ICollection<Overtime> Overtimes { get; set; } = new List<Overtime>();

    public virtual ICollection<Payroll> Payrolls { get; set; } = new List<Payroll>();
}