// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class EmployeeLeaf
{
    public long LeaveId { get; set; }

    public int EmployeeId { get; set; }

    public int LeaveTypeId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? TotalDays { get; set; }

    public string Status { get; set; }

    public int? ApprovedBy { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual LeaveType LeaveType { get; set; }
}