// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class EmployeeThr
{
    public long Thrid { get; set; }

    public int? EmployeeId { get; set; }

    public int? PayrollPeriodId { get; set; }

    public decimal? Thramount { get; set; }

    public DateTime? GeneratedDate { get; set; }

    public virtual Employee Employee { get; set; }
}