// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class LeaveType
{
    public int LeaveTypeId { get; set; }

    public string LeaveName { get; set; }

    public int? MaxDays { get; set; }

    public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; } = new List<EmployeeLeaf>();
}