// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class Overtime
{
    public long OvertimeId { get; set; }

    public int EmployeeId { get; set; }

    public DateOnly? OvertimeDate { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public decimal? TotalHours { get; set; }

    public int? ApprovedBy { get; set; }

    public string Status { get; set; }

    public virtual Employee Employee { get; set; }
}