// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class Payroll
{
    public long PayrollId { get; set; }

    public int PayrollPeriodId { get; set; }

    public int EmployeeId { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? AllowanceAmount { get; set; }

    public decimal? OvertimeAmount { get; set; }

    public decimal? Bpjsamount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? DeductionAmount { get; set; }

    public decimal? GrossSalary { get; set; }

    public decimal? NetSalary { get; set; }

    public string PayrollStatus { get; set; }

    public DateTime? GeneratedDate { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<PayrollDetail> PayrollDetails { get; set; } = new List<PayrollDetail>();

    public virtual PayrollPeriod PayrollPeriod { get; set; }
}