// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class PayrollDetail
{
    public long PayrollDetailId { get; set; }

    public long PayrollId { get; set; }

    public string ComponentType { get; set; }

    public string ComponentName { get; set; }

    public decimal? Amount { get; set; }

    public virtual Payroll Payroll { get; set; }
}