// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Application.Entities;

public partial class Position
{
    public int PositionId { get; set; }

    public string PositionName { get; set; }

    public string GradeLevel { get; set; }
}