// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class Approval
{
    [Key]
    public long ApprovalId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? ReferenceType { get; set; }

    public long? ReferenceId { get; set; }

    public int? ApproverId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? ApprovalStatus { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string? Remarks { get; set; }

    public DateTime? ApprovedAt { get; set; }
}
