// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class AuditLog
{
    public long AuditLogId { get; set; }

    public string TableName { get; set; }

    public long? RecordId { get; set; }

    public string ActionType { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public int? PerformedBy { get; set; }

    public DateTime? PerformedAt { get; set; }
}