// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class AuditLog
{
    [Key]
    public long AuditLogId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? TableName { get; set; }

    public long? RecordId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? ActionType { get; set; }

    public string? OldValue { get; set; }

    public string? NewValue { get; set; }

    public int? PerformedBy { get; set; }

    public DateTime? PerformedAt { get; set; }
}
