// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("BPJSConfigurations")]
public partial class Bpjsconfiguration
{
    [Key]
    [Column("BPJSConfigId")]
    public int BpjsconfigId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? ConfigName { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? EmployeePercentage { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? CompanyPercentage { get; set; }

    public DateOnly? EffectiveDate { get; set; }
}
