// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("EmployeeTHR")]
public partial class EmployeeThr
{
    [Key]
    [Column("THRId")]
    public long Thrid { get; set; }

    public int? EmployeeId { get; set; }

    public int? PayrollPeriodId { get; set; }

    [Column("THRAmount", TypeName = "decimal(18, 2)")]
    public decimal? Thramount { get; set; }

    public DateTime? GeneratedDate { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeThrs")]
    public virtual Employee? Employee { get; set; }
}
