// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Index("EmployeeCode", Name = "UQ__Employee__1F642548EC8F4513", IsUnique = true)]
public partial class Employee
{
    [Key]
    public int EmployeeId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeCode { get; set; } = null!;

    [StringLength(150)]
    [Unicode(false)]
    public string FullName { get; set; } = null!;

    [StringLength(150)]
    [Unicode(false)]
    public string? Email { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? PhoneNumber { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? Gender { get; set; }

    public DateOnly? BirthDate { get; set; }

    public DateOnly HireDate { get; set; }

    public DateOnly? ResignDate { get; set; }

    public int? DepartmentId { get; set; }

    public int? PositionId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? BankName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? BankAccountNumber { get; set; }

    [Column("NPWP")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Npwp { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal BasicSalary { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; } = new List<EmployeeLeaf>();

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeeThr> EmployeeThrs { get; set; } = new List<EmployeeThr>();

    [InverseProperty("Employee")]
    public virtual ICollection<Overtime> Overtimes { get; set; } = new List<Overtime>();

    [InverseProperty("Employee")]
    public virtual ICollection<Payroll> Payrolls { get; set; } = new List<Payroll>();
}
