// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class EmployeeLeaf
{
    [Key]
    public long LeaveId { get; set; }

    public int EmployeeId { get; set; }

    public int LeaveTypeId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? TotalDays { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Status { get; set; }

    public int? ApprovedBy { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeLeaves")]
    public virtual Employee Employee { get; set; } = null!;

    [ForeignKey("LeaveTypeId")]
    [InverseProperty("EmployeeLeaves")]
    public virtual LeaveType LeaveType { get; set; } = null!;
}
