// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class LeaveType
{
    [Key]
    public int LeaveTypeId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? LeaveName { get; set; }

    public int? MaxDays { get; set; }

    [InverseProperty("LeaveType")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; } = new List<EmployeeLeaf>();
}
