// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class Overtime
{
    [Key]
    public long OvertimeId { get; set; }

    public int EmployeeId { get; set; }

    public DateOnly? OvertimeDate { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? TotalHours { get; set; }

    public int? ApprovedBy { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Status { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Overtimes")]
    public virtual Employee Employee { get; set; } = null!;
}
