// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class PayrollPeriod
{
    [Key]
    public int PayrollPeriodId { get; set; }

    public int PeriodMonth { get; set; }

    public int PeriodYear { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool? IsClosed { get; set; }

    public DateTime? CreatedAt { get; set; }

    [InverseProperty("PayrollPeriod")]
    public virtual ICollection<Payroll> Payrolls { get; set; } = new List<Payroll>();
}
