// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class Payroll
{
    [Key]
    public long PayrollId { get; set; }

    public int PayrollPeriodId { get; set; }

    public int EmployeeId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BasicSalary { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? AllowanceAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? OvertimeAmount { get; set; }

    [Column("BPJSAmount", TypeName = "decimal(18, 2)")]
    public decimal? Bpjsamount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TaxAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DeductionAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? GrossSalary { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? NetSalary { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? PayrollStatus { get; set; }

    public DateTime? GeneratedDate { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Payrolls")]
    public virtual Employee Employee { get; set; } = null!;

    [InverseProperty("Payroll")]
    public virtual ICollection<PayrollDetail> PayrollDetails { get; set; } = new List<PayrollDetail>();

    [ForeignKey("PayrollPeriodId")]
    [InverseProperty("Payrolls")]
    public virtual PayrollPeriod PayrollPeriod { get; set; } = null!;
}
