// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class PayrollDetail
{
    [Key]
    public long PayrollDetailId { get; set; }

    public long PayrollId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? ComponentType { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? ComponentName { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [ForeignKey("PayrollId")]
    [InverseProperty("PayrollDetails")]
    public virtual Payroll Payroll { get; set; } = null!;
}
