// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class Position
{
    [Key]
    public int PositionId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? PositionName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? GradeLevel { get; set; }
}
