// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

public partial class TaxBracket
{
    [Key]
    public int TaxBracketId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MinAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MaxAmount { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? TaxRate { get; set; }
}
