// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_AuditLogs")]
public partial class TblAuditLog
{
    [Key]
    public long Id { get; set; }

    public long? UserId { get; set; }

    [StringLength(100)]
    public string? ModuleName { get; set; }

    [StringLength(255)]
    public string? ActionName { get; set; }

    public string? Description { get; set; }

    [StringLength(100)]
    public string? IpAddress { get; set; }

    [StringLength(500)]
    public string? BrowserInfo { get; set; }

    public DateTime CreatedDate { get; set; }
}
