// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblAuditLog
{
    public long Id { get; set; }

    public long? UserId { get; set; }

    public string ModuleName { get; set; }

    public string ActionName { get; set; }

    public string Description { get; set; }

    public string IpAddress { get; set; }

    public string BrowserInfo { get; set; }

    public DateTime CreatedDate { get; set; }
}