// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblAttendanceStatus
{
    public string Name { get; set; }

    public string Description { get; set; }
}