// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Attendances")]
public partial class TblAttendance
{
    [Key]
    public long Id { get; set; }

    public long EmployeeId { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public TimeOnly? CheckInTime { get; set; }

    public TimeOnly? CheckOutTime { get; set; }

    [StringLength(50)]
    public string AttendanceStatus { get; set; } = null!;

    [StringLength(500)]
    public string? Remarks { get; set; }

    public DateTime CreatedDate { get; set; }
}
