// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblAttendance
{
    public int AttendanceId { get; set; }

    public int EmployeeId { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public int? ShiftId { get; set; }

    public TimeOnly? ScheduledTimeIn { get; set; }

    public TimeOnly? ScheduledTimeOut { get; set; }

    public TimeOnly? ActualTimeIn { get; set; }

    public TimeOnly? ActualTimeOut { get; set; }

    public int LateMinutes { get; set; }

    public int EarlyOutMinutes { get; set; }

    public int WorkMinutes { get; set; }

    public int OvertimeMinutes { get; set; }

    public string AttendanceStatus { get; set; }

    public string Remarks { get; set; }

    public bool IsHoliday { get; set; }

    public bool IsWeekend { get; set; }

    public bool IsManualEntry { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual TblEmployee Employee { get; set; }

    public virtual TblShift Shift { get; set; }
}