// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblAllowance
{
    public int Id { get; set; }

    public string AllowanceCode { get; set; }

    public string AllowanceName { get; set; }

    public bool IsTaxable { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }
}