// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_BPJSKetenagakerjaanConfig")]
public partial class TblBpjsketenagakerjaanConfig
{
    [Key]
    public int Id { get; set; }

    [Column("JHT_EmployeeRate", TypeName = "decimal(5, 4)")]
    public decimal? JhtEmployeeRate { get; set; }

    [Column("JHT_CompanyRate", TypeName = "decimal(5, 4)")]
    public decimal? JhtCompanyRate { get; set; }

    [Column("JP_EmployeeRate", TypeName = "decimal(5, 4)")]
    public decimal? JpEmployeeRate { get; set; }

    [Column("JP_CompanyRate", TypeName = "decimal(5, 4)")]
    public decimal? JpCompanyRate { get; set; }

    [Column("JKK_CompanyRate", TypeName = "decimal(5, 4)")]
    public decimal? JkkCompanyRate { get; set; }

    [Column("JKM_CompanyRate", TypeName = "decimal(5, 4)")]
    public decimal? JkmCompanyRate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? SalaryCap { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}
