// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_BPJSKesehatanConfig")]
public partial class TblBpjskesehatanConfig
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "decimal(5, 4)")]
    public decimal EmployeeRate { get; set; }

    [Column(TypeName = "decimal(5, 4)")]
    public decimal CompanyRate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal SalaryCap { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}
