// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblBpjsketenagakerjaanConfig
{
    public int Id { get; set; }

    public decimal? JhtEmployeeRate { get; set; }

    public decimal? JhtCompanyRate { get; set; }

    public decimal? JpEmployeeRate { get; set; }

    public decimal? JpCompanyRate { get; set; }

    public decimal? JkkCompanyRate { get; set; }

    public decimal? JkmCompanyRate { get; set; }

    public decimal? SalaryCap { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}