// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblBiayaJabatanConfig
{
    public int Id { get; set; }

    public decimal? Rate { get; set; }

    public decimal? MaxMonthly { get; set; }

    public decimal? MaxYearly { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}