// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblBpjskesehatanConfig
{
    public int Id { get; set; }

    public decimal EmployeeRate { get; set; }

    public decimal CompanyRate { get; set; }

    public decimal SalaryCap { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}