// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_CompanyProfiles")]
public partial class TblCompanyProfile
{
    [Key]
    public int CompanyProfileId { get; set; }

    [StringLength(200)]
    public string CompanyName { get; set; } = null!;

    [StringLength(500)]
    public string CompanyAddress { get; set; } = null!;

    [StringLength(255)]
    public string? LogoFileName { get; set; }

    [StringLength(500)]
    public string? LogoFilePath { get; set; }

    [StringLength(50)]
    public string? PhoneNumber { get; set; }

    [StringLength(100)]
    public string? Email { get; set; }

    [StringLength(150)]
    public string? Website { get; set; }

    [StringLength(100)]
    public string? TaxNumber { get; set; }

    public bool IsActive { get; set; }

    [StringLength(100)]
    public string? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [StringLength(100)]
    public string? UpdatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }
}
