// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblCompanyProfile
{
    public int CompanyProfileId { get; set; }

    public string CompanyName { get; set; }

    public string CompanyAddress { get; set; }

    public string LogoFileName { get; set; }

    public string LogoFilePath { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string TaxNumber { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}