// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Deduction")]
public partial class TblDeduction
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? DeductionCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? DeductionName { get; set; }

    public bool IsTaxable { get; set; }

    public bool IsActive { get; set; }
}
