// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_EmployeePayroll")]
public partial class TblEmployeePayroll
{
    [Key]
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal BasicSalary { get; set; }

    [Column("PTKPCode")]
    [StringLength(10)]
    [Unicode(false)]
    public string Ptkpcode { get; set; } = null!;

    [Column("NPWP")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Npwp { get; set; }

    [Column("IsBPJSKesehatan")]
    public bool IsBpjskesehatan { get; set; }

    [Column("IsBPJSKetenagakerjaan")]
    public bool IsBpjsketenagakerjaan { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}
