// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblEmployeePayrollInfo
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public string Npwp { get; set; }

    public string Ptkpcode { get; set; }

    public decimal? BasicSalary { get; set; }

    public bool? IsBpjskesehatan { get; set; }

    public bool? IsBpjsketenagakerjaan { get; set; }
}