// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[PrimaryKey("EmployeeId", "ComponentCode", "EffectiveDate")]
[Table("tbl_EmployeeSalaryComponents")]
public partial class TblEmployeeSalaryComponent
{
    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeId { get; set; } = null!;

    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string ComponentCode { get; set; } = null!;

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime EffectiveDate { get; set; }
}
