// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_EmployeePayrollInfo")]
public partial class TblEmployeePayrollInfo
{
    [Key]
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    [Column("NPWP")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Npwp { get; set; }

    [Column("PTKPCode")]
    [StringLength(10)]
    [Unicode(false)]
    public string? Ptkpcode { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BasicSalary { get; set; }

    [Column("IsBPJSKesehatan")]
    public bool? IsBpjskesehatan { get; set; }

    [Column("IsBPJSKetenagakerjaan")]
    public bool? IsBpjsketenagakerjaan { get; set; }
}
