// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblEmployeeDeduction
{
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public int DeductionId { get; set; }

    public decimal Amount { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool IsActive { get; set; }
}