// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_EmployeeSalaryDetail")]
public partial class TblEmployeeSalaryDetail
{
    [Key]
    public Guid EmployeeSalaryDetailId { get; set; }

    public Guid EmployeeSalaryId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ComponentCode { get; set; } = null!;

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }
}
