// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblEmployeePayroll
{
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public decimal BasicSalary { get; set; }

    public string Ptkpcode { get; set; }

    public string Npwp { get; set; }

    public bool IsBpjskesehatan { get; set; }

    public bool IsBpjsketenagakerjaan { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}