// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblEmployee
{
    public int EmployeeId { get; set; }

    public string EmployeeCode { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public DateTime? BirthDate { get; set; }

    public DateTime? HireDate { get; set; }

    public DateTime? ResignDate { get; set; }

    public string Department { get; set; }

    public string Position { get; set; }

    public decimal BasicSalary { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string BankName { get; set; }

    public string BankAccountNumber { get; set; }

    public string Npwp { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public int? DefaultShift { get; set; }

    public string Ptkpcode { get; set; }

    public virtual ICollection<TblAttendance> TblAttendances { get; set; } = new List<TblAttendance>();
}