// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Holiday")]
public partial class TblHoliday
{
    [Key]
    public int Id { get; set; }

    public DateOnly HolidayDate { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string HolidayName { get; set; } = null!;

    public bool IsNationalHoliday { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }
}
