// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_LeaveType")]
public partial class TblLeaveType
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? LeaveCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? LeaveName { get; set; }

    public int? AnnualQuota { get; set; }

    public bool IsPaid { get; set; }

    public bool IsActive { get; set; }
}
