// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblLeaveType
{
    public int Id { get; set; }

    public string LeaveCode { get; set; }

    public string LeaveName { get; set; }

    public int? DefaultAnnualQuota { get; set; }

    public bool IsPaid { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string Description { get; set; }

    public bool RequireAttachment { get; set; }

    public string Gender { get; set; }
}