// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Menus")]
public partial class TblMenu
{
    [Key]
    [StringLength(255)]
    public string Id { get; set; } = null!;

    [StringLength(255)]
    public string Name { get; set; } = null!;

    [StringLength(255)]
    public string Caption { get; set; } = null!;

    [StringLength(255)]
    public string Link { get; set; } = null!;

    [StringLength(255)]
    public string? Icon { get; set; }

    public int Sort { get; set; }

    [StringLength(255)]
    public string? Css { get; set; }

    [StringLength(255)]
    public string? MenuTitle { get; set; }

    [StringLength(255)]
    public string? ParentId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? CreatedBy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? UpdatedBy { get; set; }
}
