// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblMenu
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Caption { get; set; }

    public string Link { get; set; }

    public string Icon { get; set; }

    public int Sort { get; set; }

    public string Css { get; set; }

    public string MenuTitle { get; set; }

    public string ParentId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public int? Deleted { get; set; }

    public string Description { get; set; }

    public bool IsCard { get; set; }
}