// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblOvertimeType
{
    public string OvertimeCode { get; set; }

    public string OvertimeName { get; set; }

    public string Description { get; set; }

    public bool? IsWorkingDay { get; set; }

    public bool? IsRestDay { get; set; }

    public bool? IsPublicHoliday { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}