// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblOvertimeCalculation
{
    public int Id { get; set; }

    public int OvertimeId { get; set; }

    public decimal Hour1Amount { get; set; }

    public decimal Hour2Amount { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime CalculatedDate { get; set; }
}