// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_OvertimeCalculation")]
public partial class TblOvertimeCalculation
{
    [Key]
    public int Id { get; set; }

    public int OvertimeId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Hour1Amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Hour2Amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CalculatedDate { get; set; }
}
