// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblOvertimeRate
{
    public int Id { get; set; }

    public int? HourFrom { get; set; }

    public int? HourTo { get; set; }

    public decimal? Multiplier { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public bool? IsActive { get; set; }
}