// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_OvertimeRate")]
public partial class TblOvertimeRate
{
    [Key]
    public int Id { get; set; }

    public int? HourFrom { get; set; }

    public int? HourTo { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Multiplier { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public bool? IsActive { get; set; }
}
