// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_OvertimeType")]
public partial class TblOvertimeType
{
    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string OvertimeCode { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string? OvertimeName { get; set; }

    [StringLength(255)]
    public string? Description { get; set; }

    public bool? IsWorkingDay { get; set; }

    public bool? IsRestDay { get; set; }

    public bool? IsPublicHoliday { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? UpdatedBy { get; set; }
}
