// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PayrollResult")]
public partial class TblPayrollResult
{
    [Key]
    public int Id { get; set; }

    public int PayrollRunId { get; set; }

    public int EmployeeId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BasicSalary { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Allowance { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Overtime { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? GrossSalary { get; set; }

    [Column("BPJSKesehatan", TypeName = "decimal(18, 2)")]
    public decimal? Bpjskesehatan { get; set; }

    [Column("BPJSKetenagakerjaan", TypeName = "decimal(18, 2)")]
    public decimal? Bpjsketenagakerjaan { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BiayaJabatan { get; set; }

    [Column("PPh21", TypeName = "decimal(18, 2)")]
    public decimal? Pph21 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotalDeduction { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? NetSalary { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }
}
