// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPayrollResult
{
    public int Id { get; set; }

    public int PayrollRunId { get; set; }

    public int EmployeeId { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? Allowance { get; set; }

    public decimal? Overtime { get; set; }

    public decimal? GrossSalary { get; set; }

    public decimal? Bpjskesehatan { get; set; }

    public decimal? Bpjsketenagakerjaan { get; set; }

    public decimal? BiayaJabatan { get; set; }

    public decimal? Pph21 { get; set; }

    public decimal? TotalDeduction { get; set; }

    public decimal? NetSalary { get; set; }

    public DateTime? CreatedDate { get; set; }
}