// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPayrollPolicy
{
    public int Id { get; set; }

    public string PolicyName { get; set; }

    public int WorkingDaysPerMonth { get; set; }

    public bool DeductLate { get; set; }

    public bool DeductEarlyOut { get; set; }

    public decimal LatePenaltyPerMinute { get; set; }

    public decimal EarlyOutPenaltyPerMinute { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}