// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Permissions")]
public partial class TblPermission
{
    [Key]
    public long Id { get; set; }

    [StringLength(100)]
    public string PermissionCode { get; set; } = null!;

    [StringLength(255)]
    public string PermissionName { get; set; } = null!;

    [StringLength(100)]
    public string? ModuleName { get; set; }

    [StringLength(500)]
    public string? Description { get; set; }

    public DateTime CreatedDate { get; set; }
}
