// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PTKP")]
public partial class TblPtkp
{
    [Key]
    public int Id { get; set; }

    [Column("PTKPCode")]
    [StringLength(10)]
    [Unicode(false)]
    public string Ptkpcode { get; set; } = null!;

    [Column("PTKPName")]
    [StringLength(100)]
    [Unicode(false)]
    public string? Ptkpname { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}
