// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPph21Bracket
{
    public int Id { get; set; }

    public decimal MinAmount { get; set; }

    public decimal? MaxAmount { get; set; }

    public decimal TaxRate { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}