// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PayrollPeriods")]
public partial class TblPayrollPeriod
{
    [Key]
    public long Id { get; set; }

    [StringLength(20)]
    public string PeriodCode { get; set; } = null!;

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public bool IsClosed { get; set; }

    public DateTime? ClosedDate { get; set; }

    public DateTime CreatedDate { get; set; }
}
