// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPayrollResultDetail
{
    public int Id { get; set; }

    public int PayrollResultId { get; set; }

    public string ItemType { get; set; }

    public string ItemCode { get; set; }

    public string ItemDescription { get; set; }

    public decimal? Amount { get; set; }
}