// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPermission
{
    public long Id { get; set; }

    public string PermissionCode { get; set; }

    public string PermissionName { get; set; }

    public string ModuleName { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }
}