// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PPh21Bracket")]
public partial class TblPph21Bracket
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MinAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MaxAmount { get; set; }

    [Column(TypeName = "decimal(5, 4)")]
    public decimal TaxRate { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}
