// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PayrollDetails")]
public partial class TblPayrollDetail
{
    [Key]
    public long Id { get; set; }

    public long PayrollId { get; set; }

    [StringLength(50)]
    public string ComponentType { get; set; } = null!;

    [StringLength(255)]
    public string ComponentName { get; set; } = null!;

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(500)]
    public string? Remarks { get; set; }
}
