// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PayrollResultDetail")]
public partial class TblPayrollResultDetail
{
    [Key]
    public int Id { get; set; }

    public int PayrollResultId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? ItemType { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? ItemCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? ItemDescription { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }
}
