// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Payslip")]
public partial class TblPayslip
{
    [Key]
    public int Id { get; set; }

    public int PayrollResultId { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string? FileName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? GeneratedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? GeneratedBy { get; set; }
}
