// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PayrollPolicy")]
public partial class TblPayrollPolicy
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? PolicyName { get; set; }

    public int WorkingDaysPerMonth { get; set; }

    public bool DeductLate { get; set; }

    public bool DeductEarlyOut { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal LatePenaltyPerMinute { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal EarlyOutPenaltyPerMinute { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }
}
