// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPayroll
{
    public long Id { get; set; }

    public string PayrollNumber { get; set; }

    public long EmployeeId { get; set; }

    public long PayrollPeriodId { get; set; }

    public decimal BasicSalary { get; set; }

    public decimal AllowanceAmount { get; set; }

    public decimal DeductionAmount { get; set; }

    public decimal GrossSalary { get; set; }

    public decimal NetSalary { get; set; }

    public string PayrollStatus { get; set; }

    public long? ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public DateTime CreatedDate { get; set; }
}