// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_PTKP")]
public partial class TblPtkp
{
    [Key]
    [Column("PTKPCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ptkpcode { get; set; } = null!;

    [Column("PTKPName")]
    [StringLength(255)]
    [Unicode(false)]
    public string Ptkpname { get; set; } = null!;

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? NominalYearly { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? NominalMonthly { get; set; }

    [Column("TERCategory")]
    [StringLength(1)]
    [Unicode(false)]
    public string? Tercategory { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? CreatedBy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? UpdatedBy { get; set; }
}
