// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPayslip
{
    public int Id { get; set; }

    public int PayrollResultId { get; set; }

    public string FileName { get; set; }

    public DateTime? GeneratedDate { get; set; }

    public string GeneratedBy { get; set; }
}