// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Payrolls")]
public partial class TblPayroll
{
    [Key]
    public long Id { get; set; }

    [StringLength(100)]
    public string PayrollNumber { get; set; } = null!;

    public long EmployeeId { get; set; }

    public long PayrollPeriodId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal BasicSalary { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal AllowanceAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal DeductionAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal GrossSalary { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal NetSalary { get; set; }

    [StringLength(50)]
    public string PayrollStatus { get; set; } = null!;

    public long? ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public DateTime CreatedDate { get; set; }
}
