// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Positions")]
public partial class TblPosition
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string PositionCode { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string? PositionName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? GradeLevel { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? CreatedBy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? UpdatedBy { get; set; }
}
