// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblPayrollDetail
{
    public long Id { get; set; }

    public long PayrollId { get; set; }

    public string ComponentType { get; set; }

    public string ComponentName { get; set; }

    public decimal Amount { get; set; }

    public string Remarks { get; set; }
}