// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_SalaryComponents")]
public partial class TblSalaryComponent
{
    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string ComponentCode { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string ComponentName { get; set; } = null!;

    [StringLength(20)]
    [Unicode(false)]
    public string ComponentType { get; set; } = null!;

    [StringLength(20)]
    [Unicode(false)]
    public string CalculationType { get; set; } = null!;

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DefaultAmount { get; set; }

    public bool? IsTaxable { get; set; }

    public bool? IsActive { get; set; }

    public int? SortOrder { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? CreatedBy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? UpdatedBy { get; set; }
}
