// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class TblSalaryComponent
{
    public string ComponentCode { get; set; }

    public string ComponentName { get; set; }

    public string ComponentType { get; set; }

    public string CalculationType { get; set; }

    public decimal? DefaultAmount { get; set; }

    public bool? IsTaxable { get; set; }

    public bool? IsActive { get; set; }

    public int? SortOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string Description { get; set; }

    public bool IsMandatory { get; set; }

    public bool IsBpjs { get; set; }

    public bool IsThr { get; set; }

    public bool IsProrate { get; set; }

    public bool IsOvertime { get; set; }

    public bool IsVisible { get; set; }
}