// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Table("tbl_Users")]
public partial class TblUser
{
    [Key]
    public long Id { get; set; }

    [StringLength(100)]
    public string Username { get; set; } = null!;

    [StringLength(255)]
    public string? Email { get; set; }

    [StringLength(500)]
    public string PasswordHash { get; set; } = null!;

    [StringLength(255)]
    public string? FullName { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public DateTime CreatedDate { get; set; }

    [StringLength(100)]
    public string? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    [StringLength(100)]
    public string? UpdatedBy { get; set; }
}
