// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Keyless]
public partial class VwAttendance
{
    public int EmployeeId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? EmployeeCode { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? EmployeeName { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public int? ShiftId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? ShiftCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? ShiftName { get; set; }

    [Precision(0)]
    public TimeOnly? ScheduledTimeIn { get; set; }

    [Precision(0)]
    public TimeOnly? ScheduledTimeOut { get; set; }

    [Precision(0)]
    public TimeOnly? ActualTimeIn { get; set; }

    [Precision(0)]
    public TimeOnly? ActualTimeOut { get; set; }

    public int LateMinutes { get; set; }

    public int EarlyOutMinutes { get; set; }

    public int WorkMinutes { get; set; }

    public int OvertimeMinutes { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string AttendanceStatus { get; set; } = null!;

    [StringLength(500)]
    public string? Remarks { get; set; }

    public bool IsHoliday { get; set; }

    public bool IsWeekend { get; set; }

    public bool IsManualEntry { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Position { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string Department { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string PositionDescription { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string DepartmentDescription { get; set; } = null!;
}
