// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class VwAttendance
{
    public int EmployeeId { get; set; }

    public string EmployeeCode { get; set; }

    public string EmployeeName { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public int? ShiftId { get; set; }

    public string ShiftCode { get; set; }

    public string ShiftName { get; set; }

    public TimeOnly? ScheduledTimeIn { get; set; }

    public TimeOnly? ScheduledTimeOut { get; set; }

    public TimeOnly? ActualTimeIn { get; set; }

    public TimeOnly? ActualTimeOut { get; set; }

    public int LateMinutes { get; set; }

    public int EarlyOutMinutes { get; set; }

    public int WorkMinutes { get; set; }

    public int OvertimeMinutes { get; set; }

    public string AttendanceStatus { get; set; }

    public string Remarks { get; set; }

    public bool IsHoliday { get; set; }

    public bool IsWeekend { get; set; }

    public bool IsManualEntry { get; set; }

    public string Position { get; set; }

    public string Department { get; set; }

    public string PositionDescription { get; set; }

    public string DepartmentDescription { get; set; }
}