// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class VwBranchDetail
{
    public int Id { get; set; }

    public string BranchCode { get; set; }

    public string BranchName { get; set; }

    public string Address { get; set; }

    public int? BranchHeadEmployeeId { get; set; }

    public int CompanyProfileId { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string EmployeeCode { get; set; }

    public string FullName { get; set; }

    public string CompanyName { get; set; }
}