// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Keyless]
public partial class VwEmployeeMonthlySchedule
{
    public long? RowNumber { get; set; }

    public int? EmployeeId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeCode { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string EmployeeName { get; set; } = null!;

    public int? YearNo { get; set; }

    public int? MonthNo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day1 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day2 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day3 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day4 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day5 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day6 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day7 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day8 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day9 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day10 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day11 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day12 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day13 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day14 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day15 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day16 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day17 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day18 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day19 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day20 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day21 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day22 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day23 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day24 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day25 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day26 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day27 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day28 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day29 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day30 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Day31 { get; set; }
}
