// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Keyless]
public partial class VwEmployeeSalary
{
    public int EmployeeId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeCode { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string EmployeeName { get; set; } = null!;

    public Guid? EmployeeSalaryId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Position { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Department { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? PositionDescription { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? DepartmentDescription { get; set; }
}
