// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class VwEmployeeSalary
{
    public int EmployeeId { get; set; }

    public string EmployeeCode { get; set; }

    public string EmployeeName { get; set; }

    public string Position { get; set; }

    public string Department { get; set; }

    public string PositionDescription { get; set; }

    public string DepartmentDescription { get; set; }
}