// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class VwEmployeeMonthlySchedule
{
    public long? RowNumber { get; set; }

    public int? EmployeeId { get; set; }

    public string EmployeeCode { get; set; }

    public string EmployeeName { get; set; }

    public int? YearNo { get; set; }

    public int? MonthNo { get; set; }

    public string Day1 { get; set; }

    public string Day2 { get; set; }

    public string Day3 { get; set; }

    public string Day4 { get; set; }

    public string Day5 { get; set; }

    public string Day6 { get; set; }

    public string Day7 { get; set; }

    public string Day8 { get; set; }

    public string Day9 { get; set; }

    public string Day10 { get; set; }

    public string Day11 { get; set; }

    public string Day12 { get; set; }

    public string Day13 { get; set; }

    public string Day14 { get; set; }

    public string Day15 { get; set; }

    public string Day16 { get; set; }

    public string Day17 { get; set; }

    public string Day18 { get; set; }

    public string Day19 { get; set; }

    public string Day20 { get; set; }

    public string Day21 { get; set; }

    public string Day22 { get; set; }

    public string Day23 { get; set; }

    public string Day24 { get; set; }

    public string Day25 { get; set; }

    public string Day26 { get; set; }

    public string Day27 { get; set; }

    public string Day28 { get; set; }

    public string Day29 { get; set; }

    public string Day30 { get; set; }

    public string Day31 { get; set; }
}