// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class VwLeaveRequest
{
    public long Id { get; set; }

    public string BranchCode { get; set; }

    public string BranchName { get; set; }

    public string DepartmentCode { get; set; }

    public string DepartmentName { get; set; }

    public long EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string LeaveTypeCode { get; set; }

    public string LeaveName { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int TotalDays { get; set; }

    public string Reason { get; set; }

    public bool? ApprovalStatus { get; set; }

    public long? ApprovedBy { get; set; }

    public string ApprovedByName { get; set; }

    public DateTime? ApprovedDate { get; set; }
}