// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain.Entities;

[Keyless]
public partial class VwLeaveRequest
{
    public long Id { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string BranchCode { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string? BranchName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DepartmentCode { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string? DepartmentName { get; set; }

    public long EmployeeId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? EmployeeName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string LeaveTypeCode { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string? LeaveName { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int TotalDays { get; set; }

    public string? Reason { get; set; }

    public bool? ApprovalStatus { get; set; }

    public long? ApprovedBy { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? ApprovedByName { get; set; }

    public DateTime? ApprovedDate { get; set; }
}
