// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Domain.Entities;

public partial class VwRolePermission
{
    public long? Id { get; set; }

    public string RoleCode { get; set; }

    public string MenuId { get; set; }

    public bool? CanView { get; set; }

    public bool? CanCreate { get; set; }

    public bool? CanEdit { get; set; }

    public bool? CanDelete { get; set; }

    public bool? CanExport { get; set; }

    public bool? CanApprove { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string RoleName { get; set; }

    public int? RoleLevel { get; set; }

    public string Name { get; set; }

    public int? Sort { get; set; }

    public string ParentId { get; set; }

    public string Icon { get; set; }

    public string Css { get; set; }

    public int MenuLevel { get; set; }
}