// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using App.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace App.Infrastructure.Data;

public partial class AppDBContext : DbContext
{
    public AppDBContext(DbContextOptions<AppDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<PayrollPeriod> PayrollPeriods { get; set; }

    public virtual DbSet<Serilog> Serilogs { get; set; }

    public virtual DbSet<TaxBracket> TaxBrackets { get; set; }

    public virtual DbSet<TblAllowance> TblAllowances { get; set; }

    public virtual DbSet<TblAttendance> TblAttendances { get; set; }

    public virtual DbSet<TblAttendance1> TblAttendances1 { get; set; }

    public virtual DbSet<TblAuditLog> TblAuditLogs { get; set; }

    public virtual DbSet<TblBiayaJabatanConfig> TblBiayaJabatanConfigs { get; set; }

    public virtual DbSet<TblBpjskesehatanConfig> TblBpjskesehatanConfigs { get; set; }

    public virtual DbSet<TblBpjsketenagakerjaanConfig> TblBpjsketenagakerjaanConfigs { get; set; }

    public virtual DbSet<TblBranch> TblBranches { get; set; }

    public virtual DbSet<TblCompanyProfile> TblCompanyProfiles { get; set; }

    public virtual DbSet<TblDeduction> TblDeductions { get; set; }

    public virtual DbSet<TblDepartment> TblDepartments { get; set; }

    public virtual DbSet<TblEmployee> TblEmployees { get; set; }

    public virtual DbSet<TblEmployeeAllowance> TblEmployeeAllowances { get; set; }

    public virtual DbSet<TblEmployeeDeduction> TblEmployeeDeductions { get; set; }

    public virtual DbSet<TblEmployeePayroll> TblEmployeePayrolls { get; set; }

    public virtual DbSet<TblEmployeePayrollInfo> TblEmployeePayrollInfos { get; set; }

    public virtual DbSet<TblEmployeeSalary> TblEmployeeSalaries { get; set; }

    public virtual DbSet<TblEmployeeSalaryDetail> TblEmployeeSalaryDetails { get; set; }

    public virtual DbSet<TblEmployeeShift> TblEmployeeShifts { get; set; }

    public virtual DbSet<TblEmployeeShiftSchedule> TblEmployeeShiftSchedules { get; set; }

    public virtual DbSet<TblHoliday> TblHolidays { get; set; }

    public virtual DbSet<TblLeaveRequest> TblLeaveRequests { get; set; }

    public virtual DbSet<TblLeaveType> TblLeaveTypes { get; set; }

    public virtual DbSet<TblMenu> TblMenus { get; set; }

    public virtual DbSet<TblOvertime> TblOvertimes { get; set; }

    public virtual DbSet<TblOvertimeCalculation> TblOvertimeCalculations { get; set; }

    public virtual DbSet<TblOvertimeRate> TblOvertimeRates { get; set; }

    public virtual DbSet<TblPayroll> TblPayrolls { get; set; }

    public virtual DbSet<TblPayrollDetail> TblPayrollDetails { get; set; }

    public virtual DbSet<TblPayrollPeriod> TblPayrollPeriods { get; set; }

    public virtual DbSet<TblPayrollPolicy> TblPayrollPolicies { get; set; }

    public virtual DbSet<TblPayrollResult> TblPayrollResults { get; set; }

    public virtual DbSet<TblPayrollResultDetail> TblPayrollResultDetails { get; set; }

    public virtual DbSet<TblPayrollRun> TblPayrollRuns { get; set; }

    public virtual DbSet<TblPayslip> TblPayslips { get; set; }

    public virtual DbSet<TblPermission> TblPermissions { get; set; }

    public virtual DbSet<TblPosition> TblPositions { get; set; }

    public virtual DbSet<TblPph21Bracket> TblPph21Brackets { get; set; }

    public virtual DbSet<TblPtkp> TblPtkps { get; set; }

    public virtual DbSet<TblRole> TblRoles { get; set; }

    public virtual DbSet<TblRolePermission> TblRolePermissions { get; set; }

    public virtual DbSet<TblSalaryComponent> TblSalaryComponents { get; set; }

    public virtual DbSet<TblShift> TblShifts { get; set; }

    public virtual DbSet<TblShiftPattern> TblShiftPatterns { get; set; }

    public virtual DbSet<TblShiftPatternDetail> TblShiftPatternDetails { get; set; }

    public virtual DbSet<TblUser> TblUsers { get; set; }

    public virtual DbSet<TblUserRole> TblUserRoles { get; set; }

    public virtual DbSet<VwBranchDetail> VwBranchDetails { get; set; }

    public virtual DbSet<VwEmployeeMonthlySchedule> VwEmployeeMonthlySchedules { get; set; }

    public virtual DbSet<VwEmployeeMonthlyScheduleBackup> VwEmployeeMonthlyScheduleBackups { get; set; }

    public virtual DbSet<VwEmployeeMonthlyScheduleWithoutIsRestField> VwEmployeeMonthlyScheduleWithoutIsRestFields { get; set; }

    public virtual DbSet<VwEmployeeSalary> VwEmployeeSalaries { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.AuditLogId).HasName("PK__AuditLog__EB5F6CBDAE9771B9");

            entity.Property(e => e.ActionType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PerformedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TableName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PayrollPeriod>(entity =>
        {
            entity.HasKey(e => e.PayrollPeriodId).HasName("PK__PayrollP__06190D36A30FFDD5");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsClosed).HasDefaultValue(false);
        });

        modelBuilder.Entity<Serilog>(entity =>
        {
            entity.ToTable("SERILOG");

            entity.Property(e => e.Level).HasMaxLength(16);
            entity.Property(e => e.MachineName).HasMaxLength(100);
            entity.Property(e => e.TimeStamp).HasColumnType("datetime");
            entity.Property(e => e.Username).HasMaxLength(256);
        });

        modelBuilder.Entity<TaxBracket>(entity =>
        {
            entity.HasKey(e => e.TaxBracketId).HasName("PK__TaxBrack__DE9EDED1E3ED8D2C");

            entity.Property(e => e.MaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<TblAllowance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Allo__3214EC071A21B3F6");

            entity.ToTable("tbl_Allowance");

            entity.Property(e => e.AllowanceCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.AllowanceName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsTaxable).HasDefaultValue(true);
        });

        modelBuilder.Entity<TblAttendance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Atte__3214EC07A59516EA");

            entity.ToTable("tbl_Attendance");

            entity.Property(e => e.CheckIn).HasColumnType("datetime");
            entity.Property(e => e.CheckOut).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Remarks)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblAttendance1>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Atte__3214EC07A280FC32");

            entity.ToTable("tbl_Attendances");

            entity.Property(e => e.AttendanceStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Present");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Remarks).HasMaxLength(500);
        });

        modelBuilder.Entity<TblAuditLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Audi__3214EC073B12DAF4");

            entity.ToTable("tbl_AuditLogs");

            entity.Property(e => e.ActionName).HasMaxLength(255);
            entity.Property(e => e.BrowserInfo).HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IpAddress).HasMaxLength(100);
            entity.Property(e => e.ModuleName).HasMaxLength(100);
        });

        modelBuilder.Entity<TblBiayaJabatanConfig>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Biay__3214EC07A217BE00");

            entity.ToTable("tbl_BiayaJabatanConfig");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxMonthly).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MaxYearly).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Rate).HasColumnType("decimal(5, 4)");
        });

        modelBuilder.Entity<TblBpjskesehatanConfig>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_BPJS__3214EC077D3A585E");

            entity.ToTable("tbl_BPJSKesehatanConfig");

            entity.Property(e => e.CompanyRate).HasColumnType("decimal(5, 4)");
            entity.Property(e => e.EmployeeRate).HasColumnType("decimal(5, 4)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.SalaryCap).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<TblBpjsketenagakerjaanConfig>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_BPJS__3214EC073D6C9D05");

            entity.ToTable("tbl_BPJSKetenagakerjaanConfig");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.JhtCompanyRate)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("JHT_CompanyRate");
            entity.Property(e => e.JhtEmployeeRate)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("JHT_EmployeeRate");
            entity.Property(e => e.JkkCompanyRate)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("JKK_CompanyRate");
            entity.Property(e => e.JkmCompanyRate)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("JKM_CompanyRate");
            entity.Property(e => e.JpCompanyRate)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("JP_CompanyRate");
            entity.Property(e => e.JpEmployeeRate)
                .HasColumnType("decimal(5, 4)")
                .HasColumnName("JP_EmployeeRate");
            entity.Property(e => e.SalaryCap).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<TblBranch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Bran__3214EC07F3BBDA87");

            entity.ToTable("tbl_Branches");

            entity.Property(e => e.Address)
                .HasMaxLength(191)
                .IsUnicode(false);
            entity.Property(e => e.BranchCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.BranchName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblCompanyProfile>(entity =>
        {
            entity.HasKey(e => e.CompanyProfileId).HasName("PK__tbl_Comp__0B8C9D49AEC6E4D6");

            entity.ToTable("tbl_CompanyProfiles");

            entity.Property(e => e.CompanyAddress)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogoFileName).HasMaxLength(255);
            entity.Property(e => e.LogoFilePath).HasMaxLength(500);
            entity.Property(e => e.PhoneNumber).HasMaxLength(50);
            entity.Property(e => e.TaxNumber).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Website).HasMaxLength(150);
        });

        modelBuilder.Entity<TblDeduction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Dedu__3214EC0719F7064B");

            entity.ToTable("tbl_Deduction");

            entity.Property(e => e.DeductionCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DeductionName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<TblDepartment>(entity =>
        {
            entity.HasKey(e => e.DepartmentCode).HasName("PK__Departme__B2079BED1D3A0B65");

            entity.ToTable("tbl_Departments");

            entity.Property(e => e.DepartmentCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DepartmentName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblEmployee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__tbl_Empl__7AD04F11AD6E2F2B");

            entity.ToTable("tbl_Employees");

            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.BankAccountNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BankName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.BasicSalary)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tbl_Emplo__Basic__625A9A57")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BirthDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Department)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.HireDate).HasColumnType("datetime");
            entity.Property(e => e.Npwp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NPWP");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Position)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Ptkpcode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PTKPCode");
            entity.Property(e => e.ResignDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblEmployeeAllowance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Empl__3214EC07233A1C65");

            entity.ToTable("tbl_EmployeeAllowance");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<TblEmployeeDeduction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Empl__3214EC07694504BA");

            entity.ToTable("tbl_EmployeeDeduction");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<TblEmployeePayroll>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Empl__3214EC0739A25DF7");

            entity.ToTable("tbl_EmployeePayroll");

            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsBpjskesehatan)
                .HasDefaultValue(true)
                .HasColumnName("IsBPJSKesehatan");
            entity.Property(e => e.IsBpjsketenagakerjaan)
                .HasDefaultValue(true)
                .HasColumnName("IsBPJSKetenagakerjaan");
            entity.Property(e => e.Npwp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NPWP");
            entity.Property(e => e.Ptkpcode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("TK0")
                .HasColumnName("PTKPCode");
        });

        modelBuilder.Entity<TblEmployeePayrollInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Empl__3214EC0796BD63D8");

            entity.ToTable("tbl_EmployeePayrollInfo");

            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsBpjskesehatan).HasColumnName("IsBPJSKesehatan");
            entity.Property(e => e.IsBpjsketenagakerjaan).HasColumnName("IsBPJSKetenagakerjaan");
            entity.Property(e => e.Npwp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NPWP");
            entity.Property(e => e.Ptkpcode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("PTKPCode");
        });

        modelBuilder.Entity<TblEmployeeSalary>(entity =>
        {
            entity.HasKey(e => e.EmployeeId);

            entity.ToTable("tbl_EmployeeSalary");

            entity.Property(e => e.EmployeeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tbl_Emplo__IsAct__45544755");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblEmployeeSalaryDetail>(entity =>
        {
            entity.HasKey(e => new { e.EmployeeId, e.ComponentCode });

            entity.ToTable("tbl_EmployeeSalaryDetail");

            entity.Property(e => e.ComponentCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblEmployeeShift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Empl__3214EC077F3E5CD0");

            entity.ToTable("tbl_EmployeeShift");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblEmployeeShiftSchedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Empl__3214EC0743913644");

            entity.ToTable("tbl_EmployeeShiftSchedule");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Remarks).HasMaxLength(500);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WorkDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblHoliday>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Holi__3214EC078D0D7029");

            entity.ToTable("tbl_Holiday");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HolidayDate).HasColumnType("datetime");
            entity.Property(e => e.HolidayName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblLeaveRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Leav__3214EC07BFEC9789");

            entity.ToTable("tbl_LeaveRequests");

            entity.Property(e => e.ApprovalStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.BranchCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DepartmentCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LeaveTypeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblLeaveType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Leav__3214EC07F7810D3A");

            entity.ToTable("tbl_LeaveType");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.LeaveCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LeaveName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblMenu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Menu__3214EC0731CED028");

            entity.ToTable("tbl_Menus");

            entity.Property(e => e.Id).HasMaxLength(255);
            entity.Property(e => e.Caption)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Css).HasMaxLength(255);
            entity.Property(e => e.Icon).HasMaxLength(255);
            entity.Property(e => e.Link)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MenuTitle).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ParentId).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblOvertime>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Over__3214EC07327E2243");

            entity.ToTable("tbl_Overtime");

            entity.Property(e => e.ApprovedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ApprovedDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.Reason)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("DRAFT");
            entity.Property(e => e.TotalHours).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblOvertimeCalculation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Over__3214EC07C895A1F2");

            entity.ToTable("tbl_OvertimeCalculation");

            entity.Property(e => e.CalculatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Hour1Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Hour2Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<TblOvertimeRate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Over__3214EC07228AC5FC");

            entity.ToTable("tbl_OvertimeRate");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Multiplier).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<TblPayroll>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC07889A2AFC");

            entity.ToTable("tbl_Payrolls");

            entity.Property(e => e.AllowanceAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DeductionAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GrossSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PayrollNumber)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PayrollStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Draft");
        });

        modelBuilder.Entity<TblPayrollDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC07D8ED555F");

            entity.ToTable("tbl_PayrollDetails");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ComponentName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ComponentType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Remarks).HasMaxLength(500);
        });

        modelBuilder.Entity<TblPayrollPeriod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC073A1E7A1B");

            entity.ToTable("tbl_PayrollPeriods");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PeriodCode)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<TblPayrollPolicy>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC0783AFC037");

            entity.ToTable("tbl_PayrollPolicy");

            entity.Property(e => e.EarlyOutPenaltyPerMinute).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LatePenaltyPerMinute).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PolicyName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TblPayrollResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC07ECCB6119");

            entity.ToTable("tbl_PayrollResult");

            entity.Property(e => e.Allowance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BiayaJabatan).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Bpjskesehatan)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("BPJSKesehatan");
            entity.Property(e => e.Bpjsketenagakerjaan)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("BPJSKetenagakerjaan");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.GrossSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Overtime).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Pph21)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("PPh21");
            entity.Property(e => e.TotalDeduction).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<TblPayrollResultDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC0736ADDCE2");

            entity.ToTable("tbl_PayrollResultDetail");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ItemDescription)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ItemType)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TblPayrollRun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC07BAD228BC");

            entity.ToTable("tbl_PayrollRun");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TblPayslip>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Pays__3214EC07C0CD4D78");

            entity.ToTable("tbl_Payslip");

            entity.Property(e => e.FileName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.GeneratedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.GeneratedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TblPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Perm__3214EC07EF48C5E8");

            entity.ToTable("tbl_Permissions");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ModuleName).HasMaxLength(100);
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<TblPosition>(entity =>
        {
            entity.HasKey(e => e.PositionCode).HasName("PK__Position__60BB9A799D578AAB");

            entity.ToTable("tbl_Positions");

            entity.Property(e => e.PositionCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.GradeLevel)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PositionName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblPph21Bracket>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_PPh2__3214EC07A501B6AF");

            entity.ToTable("tbl_PPh21Bracket");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 4)");
        });

        modelBuilder.Entity<TblPtkp>(entity =>
        {
            entity.HasKey(e => e.Ptkpcode);

            entity.ToTable("tbl_PTKP");

            entity.Property(e => e.Ptkpcode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PTKPCode");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.NominalMonthly).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NominalYearly).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Ptkpname)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("PTKPName");
            entity.Property(e => e.Tercategory)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("TERCategory");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Role__3214EC075E5D7AB3");

            entity.ToTable("tbl_Roles");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Role__3214EC0775A16E64");

            entity.ToTable("tbl_RolePermissions");

            entity.Property(e => e.AssignedDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<TblSalaryComponent>(entity =>
        {
            entity.HasKey(e => e.ComponentCode).HasName("PK__tbl_Sala__898CFBF91F9E5C13");

            entity.ToTable("tbl_SalaryComponents");

            entity.Property(e => e.ComponentCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CalculationType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ComponentName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ComponentType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DefaultAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblShift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Shif__3214EC07B7E95F55");

            entity.ToTable("tbl_Shift");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsOvernight).HasDefaultValue(false);
            entity.Property(e => e.ShiftCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ShiftName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.WorkingHours).HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<TblShiftPattern>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Shif__3214EC0754CDCD0A");

            entity.ToTable("tbl_ShiftPattern");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.PatternCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PatternName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblShiftPatternDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Shif__3214EC07695CC16B");

            entity.ToTable("tbl_ShiftPatternDetail");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_User__3214EC0794A326C3");

            entity.ToTable("tbl_Users");

            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TblUserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_User__3214EC075F0D6048");

            entity.ToTable("tbl_UserRoles");

            entity.Property(e => e.AssignedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<VwBranchDetail>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_BranchDetails");

            entity.Property(e => e.Address)
                .HasMaxLength(191)
                .IsUnicode(false);
            entity.Property(e => e.BranchCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.BranchName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CompanyName).HasMaxLength(200);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EmployeeCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<VwEmployeeMonthlySchedule>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_EmployeeMonthlySchedule");

            entity.Property(e => e.Day1)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day10)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day11)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day12)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day13)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day14)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day15)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day16)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day17)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day18)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day19)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day2)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day20)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day21)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day22)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day23)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day24)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day25)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day26)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day27)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day28)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day29)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day3)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day30)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day31)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day4)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day5)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day6)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day7)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day8)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day9)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwEmployeeMonthlyScheduleBackup>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_EmployeeMonthlySchedule_backup");

            entity.Property(e => e.Day1)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day10)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day11)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day12)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day13)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day14)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day15)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day16)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day17)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day18)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day19)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day2)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day20)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day21)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day22)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day23)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day24)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day25)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day26)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day27)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day28)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day29)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day3)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day30)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day31)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day4)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day5)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day6)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day7)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day8)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day9)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwEmployeeMonthlyScheduleWithoutIsRestField>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_EmployeeMonthlySchedule_Without_IsRest_Field");

            entity.Property(e => e.Day1)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day10)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day11)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day12)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day13)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day14)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day15)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day16)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day17)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day18)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day19)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day2)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day20)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day21)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day22)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day23)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day24)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day25)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day26)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day27)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day28)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day29)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day3)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day30)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day31)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day4)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day5)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day6)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day7)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day8)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Day9)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwEmployeeSalary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_EmployeeSalary");

            entity.Property(e => e.Department)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DepartmentDescription)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Position)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PositionDescription)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}