// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using App.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace App.Infrastructure.Data;

public partial class AppDBContext : DbContext
{
    public AppDBContext(DbContextOptions<AppDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Approval> Approvals { get; set; }

    public virtual DbSet<Attendance> Attendances { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Bpjsconfiguration> Bpjsconfigurations { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeLeaf> EmployeeLeaves { get; set; }

    public virtual DbSet<EmployeeThr> EmployeeThrs { get; set; }

    public virtual DbSet<LeaveType> LeaveTypes { get; set; }

    public virtual DbSet<Overtime> Overtimes { get; set; }

    public virtual DbSet<Payroll> Payrolls { get; set; }

    public virtual DbSet<PayrollDetail> PayrollDetails { get; set; }

    public virtual DbSet<PayrollPeriod> PayrollPeriods { get; set; }

    public virtual DbSet<Position> Positions { get; set; }

    public virtual DbSet<TaxBracket> TaxBrackets { get; set; }

    public virtual DbSet<TblAttendance> TblAttendances { get; set; }

    public virtual DbSet<TblAuditLog> TblAuditLogs { get; set; }

    public virtual DbSet<TblCompanyProfile> TblCompanyProfiles { get; set; }

    public virtual DbSet<TblEmployee> TblEmployees { get; set; }

    public virtual DbSet<TblLeaveRequest> TblLeaveRequests { get; set; }

    public virtual DbSet<TblMenu> TblMenus { get; set; }

    public virtual DbSet<TblPayroll> TblPayrolls { get; set; }

    public virtual DbSet<TblPayrollDetail> TblPayrollDetails { get; set; }

    public virtual DbSet<TblPayrollPeriod> TblPayrollPeriods { get; set; }

    public virtual DbSet<TblPermission> TblPermissions { get; set; }

    public virtual DbSet<TblRole> TblRoles { get; set; }

    public virtual DbSet<TblRolePermission> TblRolePermissions { get; set; }

    public virtual DbSet<TblUser> TblUsers { get; set; }

    public virtual DbSet<TblUserRole> TblUserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Approval>(entity =>
        {
            entity.HasKey(e => e.ApprovalId).HasName("PK__Approval__328477F476A675FE");

            entity.Property(e => e.ApprovalStatus)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ReferenceType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Remarks)
                .HasMaxLength(500)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.HasKey(e => e.AttendanceId).HasName("PK__Attendan__8B69261C89767F79");

            entity.Property(e => e.LateMinutes).HasDefaultValue(0);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.WorkHours).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Employee).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Attendanc__Emplo__5441852A");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.AuditLogId).HasName("PK__AuditLog__EB5F6CBDAE9771B9");

            entity.Property(e => e.ActionType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PerformedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TableName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Bpjsconfiguration>(entity =>
        {
            entity.HasKey(e => e.BpjsconfigId).HasName("PK__BPJSConf__D4D800C9D76F8435");

            entity.ToTable("BPJSConfigurations");

            entity.Property(e => e.BpjsconfigId).HasColumnName("BPJSConfigId");
            entity.Property(e => e.CompanyPercentage).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.ConfigName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmployeePercentage).HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentId).HasName("PK__Departme__B2079BED1D3A0B65");

            entity.Property(e => e.DepartmentName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__Employee__7AD04F1144288E43");

            entity.HasIndex(e => e.EmployeeCode, "UQ__Employee__1F642548EC8F4513").IsUnique();

            entity.Property(e => e.BankAccountNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BankName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Npwp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NPWP");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<EmployeeLeaf>(entity =>
        {
            entity.HasKey(e => e.LeaveId).HasName("PK__Employee__796DB959B7D42184");

            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeLeaves)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EmployeeL__Emplo__59063A47");

            entity.HasOne(d => d.LeaveType).WithMany(p => p.EmployeeLeaves)
                .HasForeignKey(d => d.LeaveTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EmployeeL__Leave__59FA5E80");
        });

        modelBuilder.Entity<EmployeeThr>(entity =>
        {
            entity.HasKey(e => e.Thrid).HasName("PK__Employee__5C59F774AC6BC253");

            entity.ToTable("EmployeeTHR");

            entity.Property(e => e.Thrid).HasColumnName("THRId");
            entity.Property(e => e.Thramount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("THRAmount");

            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeThrs)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK__EmployeeT__Emplo__6EF57B66");
        });

        modelBuilder.Entity<LeaveType>(entity =>
        {
            entity.HasKey(e => e.LeaveTypeId).HasName("PK__LeaveTyp__43BE8F14F728B318");

            entity.Property(e => e.LeaveName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Overtime>(entity =>
        {
            entity.HasKey(e => e.OvertimeId).HasName("PK__Overtime__F61430B839FEDE42");

            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TotalHours).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Employee).WithMany(p => p.Overtimes)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Overtimes__Emplo__5CD6CB2B");
        });

        modelBuilder.Entity<Payroll>(entity =>
        {
            entity.HasKey(e => e.PayrollId).HasName("PK__Payrolls__99DFC6723B242460");

            entity.Property(e => e.AllowanceAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Bpjsamount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("BPJSAmount");
            entity.Property(e => e.DeductionAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GeneratedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.GrossSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OvertimeAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PayrollStatus)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Employee).WithMany(p => p.Payrolls)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payrolls__Employ__656C112C");

            entity.HasOne(d => d.PayrollPeriod).WithMany(p => p.Payrolls)
                .HasForeignKey(d => d.PayrollPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payrolls__Payrol__6477ECF3");
        });

        modelBuilder.Entity<PayrollDetail>(entity =>
        {
            entity.HasKey(e => e.PayrollDetailId).HasName("PK__PayrollD__010127C9C518D4D0");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ComponentName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ComponentType)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Payroll).WithMany(p => p.PayrollDetails)
                .HasForeignKey(d => d.PayrollId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PayrollDe__Payro__68487DD7");
        });

        modelBuilder.Entity<PayrollPeriod>(entity =>
        {
            entity.HasKey(e => e.PayrollPeriodId).HasName("PK__PayrollP__06190D36A30FFDD5");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsClosed).HasDefaultValue(false);
        });

        modelBuilder.Entity<Position>(entity =>
        {
            entity.HasKey(e => e.PositionId).HasName("PK__Position__60BB9A799D578AAB");

            entity.Property(e => e.GradeLevel)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PositionName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TaxBracket>(entity =>
        {
            entity.HasKey(e => e.TaxBracketId).HasName("PK__TaxBrack__DE9EDED1E3ED8D2C");

            entity.Property(e => e.MaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<TblAttendance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Atte__3214EC07A280FC32");

            entity.ToTable("tbl_Attendances");

            entity.Property(e => e.AttendanceStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Present");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Remarks).HasMaxLength(500);
        });

        modelBuilder.Entity<TblAuditLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Audi__3214EC073B12DAF4");

            entity.ToTable("tbl_AuditLogs");

            entity.Property(e => e.ActionName).HasMaxLength(255);
            entity.Property(e => e.BrowserInfo).HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IpAddress).HasMaxLength(100);
            entity.Property(e => e.ModuleName).HasMaxLength(100);
        });

        modelBuilder.Entity<TblCompanyProfile>(entity =>
        {
            entity.HasKey(e => e.CompanyProfileId).HasName("PK__tbl_Comp__0B8C9D49AEC6E4D6");

            entity.ToTable("tbl_CompanyProfiles");

            entity.Property(e => e.CompanyAddress)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogoFileName).HasMaxLength(255);
            entity.Property(e => e.LogoFilePath).HasMaxLength(500);
            entity.Property(e => e.PhoneNumber).HasMaxLength(50);
            entity.Property(e => e.TaxNumber).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Website).HasMaxLength(150);
        });

        modelBuilder.Entity<TblEmployee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__tbl_Empl__7AD04F11AD6E2F2B");

            entity.ToTable("tbl_Employees");

            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.BankAccountNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BankName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Department)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Npwp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NPWP");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Position)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblLeaveRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Leav__3214EC0753668F16");

            entity.ToTable("tbl_LeaveRequests");

            entity.Property(e => e.ApprovalStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LeaveType)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TblMenu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Menu__3214EC0731CED028");

            entity.ToTable("tbl_Menus");

            entity.Property(e => e.Id).HasMaxLength(255);
            entity.Property(e => e.Caption)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Css).HasMaxLength(255);
            entity.Property(e => e.Icon).HasMaxLength(255);
            entity.Property(e => e.Link)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MenuTitle).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ParentId).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblPayroll>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC07889A2AFC");

            entity.ToTable("tbl_Payrolls");

            entity.Property(e => e.AllowanceAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BasicSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DeductionAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GrossSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PayrollNumber)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PayrollStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Draft");
        });

        modelBuilder.Entity<TblPayrollDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC07D8ED555F");

            entity.ToTable("tbl_PayrollDetails");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ComponentName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ComponentType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Remarks).HasMaxLength(500);
        });

        modelBuilder.Entity<TblPayrollPeriod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Payr__3214EC073A1E7A1B");

            entity.ToTable("tbl_PayrollPeriods");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PeriodCode)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<TblPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Perm__3214EC07EF48C5E8");

            entity.ToTable("tbl_Permissions");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ModuleName).HasMaxLength(100);
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<TblRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Role__3214EC075E5D7AB3");

            entity.ToTable("tbl_Roles");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<TblRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_Role__3214EC0775A16E64");

            entity.ToTable("tbl_RolePermissions");

            entity.Property(e => e.AssignedDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<TblUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_User__3214EC0794A326C3");

            entity.ToTable("tbl_Users");

            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TblUserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_User__3214EC075F0D6048");

            entity.ToTable("tbl_UserRoles");

            entity.Property(e => e.AssignedDate).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}