// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using App.Infrastructure.Data;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace App.Infrastructure.Data
{
    public partial interface IAppDBContextProcedures
    {
        Task<int> sp_SaveEmployeeSalaryAsync(IEnumerable<Type_EmployeeSalary> employeeSalaries, IEnumerable<Type_EmployeeSalaryDetail> employeeSalaryDetails, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
